apiVersion: batch/v1
kind: CronJob
metadata:
  name: citation-ttl-cleanup
  namespace: ask-maas
  labels:
    app: citation-expander
    component: cleanup
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: citation-expander
            component: cleanup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: citation-expander
          containers:
          - name: cleanup
            image: citation-expander:latest
            imagePullPolicy: Always
            command: ["python", "-c"]
            args:
              - |
                import os
                import sys
                import logging
                from worker.jobs import cleanup_expired_citations
                
                logging.basicConfig(level=logging.INFO)
                logger = logging.getLogger(__name__)
                
                try:
                    logger.info("Starting citation TTL cleanup job")
                    result = cleanup_expired_citations()
                    logger.info(f"Cleanup completed: {result}")
                    sys.exit(0)
                except Exception as e:
                    logger.error(f"Cleanup failed: {e}")
                    sys.exit(1)
            env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: QDRANT_URL
              value: "http://qdrant:6333"
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: citation-expander-monitoring
  namespace: ask-maas
  labels:
    app: citation-expander
data:
  prometheus-rules.yaml: |
    groups:
    - name: citation-expander
      interval: 30s
      rules:
      - alert: CitationExpanderHighErrorRate
        expr: rate(citation_fetched_err_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: citation-expander
        annotations:
          summary: "High error rate in citation fetching"
          description: "Citation expander has error rate > 10% for 5 minutes"
      
      - alert: CitationQueueBacklog
        expr: citation_queue_depth > 100
        for: 10m
        labels:
          severity: warning
          service: citation-expander
        annotations:
          summary: "Large citation processing queue"
          description: "Citation queue has > 100 items for 10 minutes"
      
      - alert: CitationExpanderDown
        expr: up{job="citation-expander"} == 0
        for: 2m
        labels:
          severity: critical
          service: citation-expander
        annotations:
          summary: "Citation expander is down"
          description: "Citation expander service is not responding"
