apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-article-site
  namespace: ask-maas-frontend
  labels:
    app: ghost-article-site
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-article-site
  template:
    metadata:
      labels:
        app: ghost-article-site
        version: v1
    spec:
      containers:
      - name: ghost-site
        image: image-registry.openshift-image-registry.svc:5000/ask-maas-frontend/ghost-site:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://ask-maas-api.apps.${CLUSTER_DOMAIN}"  # Replace with your cluster domain
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-article-site-service
  namespace: ask-maas-frontend
  labels:
    app: ghost-article-site
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ghost-article-site