apiVersion: apps/v1
kind: Deployment
metadata:
  name: tei-bge-m3-embeddings
  namespace: ask-maas-models
  labels:
    app: tei-embeddings
    model: bge-m3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tei-embeddings
  template:
    metadata:
      labels:
        app: tei-embeddings
        model: bge-m3
        sidecar.istio.io/inject: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: kserve-service-account
      containers:
      - name: tei-server
        image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2
        args:
          - --model-id
          - BAAI/bge-m3
          - --port
          - "8080"
          - --json-output
          - --max-batch-tokens
          - "16384"
          - --max-batch-requests
          - "32"
          - --max-client-batch-size
          - "32"
          - --tokenization-workers
          - "4"
        env:
          - name: RUST_LOG
            value: "info"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-credentials
                key: token
                optional: true
          - name: HF_HOME
            value: "/data/cache"
          - name: TRANSFORMERS_CACHE
            value: "/data/cache"
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9090
            name: metrics
            protocol: TCP
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
          - name: model-cache
            mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: tei-embeddings-cache
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tei-embeddings
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: tei-embeddings-service
  namespace: ask-maas-models
  labels:
    app: tei-embeddings
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: tei-embeddings
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tei-embeddings-cache
  namespace: ask-maas-models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-cephfs  # Adjust based on your storage class
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tei-embeddings-hpa
  namespace: ask-maas-models
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tei-bge-m3-embeddings
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
