apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-mixtral-8x7b
  namespace: ask-maas-models
  labels:
    app: vllm-model
    model: mixtral-8x7b
    component: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-model
      model: mixtral-8x7b
  template:
    metadata:
      labels:
        app: vllm-model
        model: mixtral-8x7b
        component: model-serving
    spec:
      serviceAccountName: vllm-sa
      containers:
      - name: vllm-runtime
        image: vllm/vllm-openai:v0.5.0.post1
        imagePullPolicy: IfNotPresent
        command:
          - python3
          - -m
          - vllm.entrypoints.openai.api_server
        args:
          # Mixtral 8x7B with AWQ quantization for L40S GPU
          - --model
          - TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ
          - --quantization
          - awq
          - --dtype
          - auto
          - --port
          - "8080"
          - --served-model-name
          - mixtral-8x7b-instruct
          - --trust-remote-code
          - --download-dir
          - /models-cache
          # Optimized for L40S with 46GB VRAM
          - --gpu-memory-utilization
          - "0.90"  # Use 90% of 46GB = ~41GB for model
          - --max-model-len
          - "8192"  # Reasonable context for L40S
          - --max-num-seqs
          - "64"     # Good batch size for L40S
          - --max-num-batched-tokens
          - "8192"
          - --swap-space
          - "8"  # 8GB swap space
          - --kv-cache-dtype
          - "auto"
          - --enforce-eager
        env:
          - name: VLLM_WORKER_MULTIPROC_METHOD
            value: "spawn"
          - name: CUDA_VISIBLE_DEVICES
            value: "0"
          - name: TRANSFORMERS_CACHE
            value: "/tmp/transformers-cache"
          - name: HF_HOME
            value: "/tmp/hf-home"
          - name: HOME
            value: "/tmp"
          - name: VLLM_CACHE_DIR
            value: "/tmp/vllm-cache"
          - name: FLASHINFER_CACHE_DIR
            value: "/tmp/flashinfer-cache"
          # L40S optimizations
          - name: TORCH_CUDA_ARCH_LIST
            value: "8.9"
          - name: PYTORCH_CUDA_ALLOC_CONF
            value: "max_split_size_mb:1024,expandable_segments:True"
          - name: TOKENIZERS_PARALLELISM
            value: "true"
          - name: VLLM_ATTENTION_BACKEND
            value: "FLASH_ATTN"
          - name: RAY_memory_monitor_refresh_ms
            value: "0"
        resources:
          requests:
            cpu: "3"
            memory: "24Gi"   # Need more system memory for larger model
            nvidia.com/gpu: "1"
          limits:
            cpu: "4"
            memory: "28Gi"   # Use most of the 29GB available
            nvidia.com/gpu: "1"
        volumeMounts:
          - name: model-cache
            mountPath: /models-cache
          - name: shm
            mountPath: /dev/shm
          - name: tmp-cache
            mountPath: /tmp
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180  # Mixtral needs more time to load
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 30  # Allow up to 15 minutes for startup
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 900
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: vllm-model-cache-mixtral
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi  # Larger shared memory for Mixtral
        - name: tmp-cache
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: In
                values:
                - "true"
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-L40S  # Target L40S specifically
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache-mixtral
  namespace: ask-maas-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Mixtral needs more storage
  storageClassName: gp3-csi  # Use appropriate storage class
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-mixtral-service
  namespace: ask-maas-models
  labels:
    app: vllm-model
    model: mixtral-8x7b
spec:
  selector:
    app: vllm-model
    model: mixtral-8x7b
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
